name: Build and deploy Blazor App
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2#Setup .NET Core SDK
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:# Use latest version of dotnet 7
          dotnet-version: '7.0.x'# include pre-release of dotnet
          include-prerelease: true
       
      - name: Build with dotnet# run the command for build the dotnet app
        run: dotnet build --configuration Release

      - name: dotnet publish# run the command to pack the build files and dependencies into folder for deployment
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job#Reference a specific upload artifact
        uses: actions/upload-artifact@v2

        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'# use deploy-to-webapp step in the job and look at the output of the dependent job. Then find the webapp-url and set it for URL in the environment
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job#Reference a specific download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app
